name: Decompile APK and Parse Smali

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  decompile_and_parse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y apktool

      - name: Download APK
        run: |
          curl -L "https://github.com/KometTeam/max-dumper/releases/latest/download/ru.oneme.app.apk" -o app.apk

      - name: Decompile APK
        run: |
          apktool d -f app.apk -o decompiled_out

      - name: Extract PmsKeys
        run: |
          python3 pms_extract.py decompiled_out -o pmskeys.json --verbose

      - name: Commit and Push results
        id: commit_step
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          DIFF_CONTENT=$(git diff --unified=0 pmskeys.json | sed -n '/^[+-][^+-]/p' | head -c 3000)
          
          echo "diff_text<<EOF" >> $GITHUB_OUTPUT
          echo "$DIFF_CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          git add pmskeys.json
          if git commit -m "Update parsed smali keys: $(date +'%Y-%m-%d %H:%M')"; then
            git push
            # Capture the NEW commit SHA
            NEW_SHA=$(git rev-parse HEAD)
            echo "new_sha=$NEW_SHA" >> $GITHUB_OUTPUT
            echo "updated=true" >> $GITHUB_OUTPUT
          else
            echo "No changes to commit"
            echo "updated=false" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send Telegram Notification
        if: steps.commit_step.outputs.updated == 'true'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            *New PmsKeys found!*
            
            *Changes:*
            ```diff
            ${{ steps.commit_step.outputs.diff_text }}
            ```
            
            [View Full Commit](https://github.com/${{ github.repository }}/commit/${{ steps.commit_step.outputs.new_sha }})
